In [1]:
import numpy as np 

**np.sort**

Return a sorted copy of an array 

In [3]:

a = np.random.randint(1,100,15)
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[62, 50, 85, 88],
       [87,  5, 99, 64],
       [99, 72, 55, 91],
       [49, 81,  8, 19],
       [61,  9,  9, 78],
       [56, 21,  1, 68]])

In [5]:
np.sort(a)

array([ 5,  8, 10, 13, 17, 19, 20, 38, 48, 74, 81, 86, 88, 89, 94])

In [6]:
np.sort(b)  # row wise sorting 

array([[50, 62, 85, 88],
       [ 5, 64, 87, 99],
       [55, 72, 91, 99],
       [ 8, 19, 49, 81],
       [ 9,  9, 61, 78],
       [ 1, 21, 56, 68]])

In [7]:
np.sort(b,axis = 0) #col wise sorting 

array([[49,  5,  1, 19],
       [56,  9,  8, 64],
       [61, 21,  9, 68],
       [62, 50, 55, 78],
       [87, 72, 85, 88],
       [99, 81, 99, 91]])

In [8]:
np.sort(a)[::-1]

array([94, 89, 88, 86, 81, 74, 48, 38, 20, 19, 17, 13, 10,  8,  5])

**np.append**

In [10]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [11]:
np.append(a,200)

array([ 38,   8,  81,  74,   5,  89,  19,  20,  17,  48,  86,  94,  10,
        88,  13, 200])

In [12]:
b

array([[62, 50, 85, 88],
       [87,  5, 99, 64],
       [99, 72, 55, 91],
       [49, 81,  8, 19],
       [61,  9,  9, 78],
       [56, 21,  1, 68]])

In [13]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[62., 50., 85., 88.,  1.],
       [87.,  5., 99., 64.,  1.],
       [99., 72., 55., 91.,  1.],
       [49., 81.,  8., 19.,  1.],
       [61.,  9.,  9., 78.,  1.],
       [56., 21.,  1., 68.,  1.]])

In [14]:
b.shape[0]

6

In [15]:
np.ones((6,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

**np.concatenate**

In [17]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)


In [18]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d),axis = 1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

**np.unique**

In [21]:
e = np.array([1,1,2,2,3,3,4,4,5,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6])

In [22]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

**np.expand_dims**

In [24]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [25]:
np.expand_dims(a,axis =0)

array([[38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13]])

In [26]:
np.expand_dims(a,axis =0).shape

(1, 15)

In [27]:
np.expand_dims(a,axis =1) 

array([[38],
       [ 8],
       [81],
       [74],
       [ 5],
       [89],
       [19],
       [20],
       [17],
       [48],
       [86],
       [94],
       [10],
       [88],
       [13]])

**np.where**

In [29]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [30]:
# find all indicides with value greater than 50 
np.where(a>50)

(array([ 2,  3,  5, 10, 11, 13], dtype=int64),)

In [31]:
#replace all values >50 with 0 
np.where(a>50,0,a)

array([38,  8,  0,  0,  5,  0, 19, 20, 17, 48,  0,  0, 10,  0, 13])

In [32]:
np.where(a%2==0,0,a)


array([ 0,  0, 81,  0,  5, 89, 19,  0, 17,  0,  0,  0,  0,  0, 13])

**np.argmax**

In [34]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [35]:
np.argmax(a)

11

In [36]:
b

array([[62, 50, 85, 88],
       [87,  5, 99, 64],
       [99, 72, 55, 91],
       [49, 81,  8, 19],
       [61,  9,  9, 78],
       [56, 21,  1, 68]])

In [37]:
np.argmax(b,axis = 0)


array([2, 3, 1, 2], dtype=int64)

In [38]:
np.argmax(b,axis = 1)


array([3, 2, 0, 1, 3, 3], dtype=int64)

**np.argmin**

In [40]:
print(a)
np.argmin(a)


[38  8 81 74  5 89 19 20 17 48 86 94 10 88 13]


4

**np.cumsum**

In [42]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [43]:
np.cumsum(a)

array([ 38,  46, 127, 201, 206, 295, 314, 334, 351, 399, 485, 579, 589,
       677, 690])

In [44]:
np.cumsum(b)

array([  62,  112,  197,  285,  372,  377,  476,  540,  639,  711,  766,
        857,  906,  987,  995, 1014, 1075, 1084, 1093, 1171, 1227, 1248,
       1249, 1317])

In [45]:
b

array([[62, 50, 85, 88],
       [87,  5, 99, 64],
       [99, 72, 55, 91],
       [49, 81,  8, 19],
       [61,  9,  9, 78],
       [56, 21,  1, 68]])

In [46]:
np.cumsum(b,axis = 0)


array([[ 62,  50,  85,  88],
       [149,  55, 184, 152],
       [248, 127, 239, 243],
       [297, 208, 247, 262],
       [358, 217, 256, 340],
       [414, 238, 257, 408]])

In [47]:
np.cumsum(b,axis = 1)


array([[ 62, 112, 197, 285],
       [ 87,  92, 191, 255],
       [ 99, 171, 226, 317],
       [ 49, 130, 138, 157],
       [ 61,  70,  79, 157],
       [ 56,  77,  78, 146]])

**np.cumprod**

In [49]:
print(a)
np.cumprod(a)

[38  8 81 74  5 89 19 20 17 48 86 94 10 88 13]


array([         38,         304,       24624,     1822176,     9110880,
         810868320, -1773371104, -1107683712, -1650753920, -1926776832,
        1800916992,  1782472704,   644857856,   912916480, -1016987648])

In [50]:
d = np.array([1,2,3,4,5])
np.cumprod(d)

array([  1,   2,   6,  24, 120])

**np.percentile**

In [52]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [53]:
np.percentile(a,50)

38.0

In [54]:
np.median(a)

38.0

**np.histogram**

In [56]:
print(a)
np.histogram(a,bins=[10,20,30,40,50,60,70,80,90,100]) # 10 to 20, 1 item is there 

[38  8 81 74  5 89 19 20 17 48 86 94 10 88 13]


(array([4, 1, 1, 1, 0, 0, 1, 4, 1], dtype=int64),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [57]:
np.histogram(a,bins=[0,50,100])

(array([9, 6], dtype=int64), array([  0,  50, 100]))

**np.corrcoef**

In [59]:
salary = np.array([200000,400000,250000,350000,600000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

**np.isin**

In [61]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [62]:
items = [10,20,30,40,50,60,70,80]

In [63]:
a[np.isin(a,items)]

array([20, 10])

**np.flip**

In [65]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [66]:
np.flip(a)

array([13, 88, 10, 94, 86, 48, 17, 20, 19, 89,  5, 74, 81,  8, 38])

**np.put**

In [68]:
a

array([38,  8, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [69]:
np.put(a,[0,1],[42,82])

In [70]:
a

array([42, 82, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

**np.delete**

In [72]:
a

array([42, 82, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [73]:
np.delete(a,0)

array([82, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [74]:
np.delete(a,[0,2,4])


array([82, 74, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

**Set functions**

In [76]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])


In [77]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [78]:
np.intersect1d(m,n)


array([3, 4, 5])

In [79]:
np.setdiff1d(m,n)


array([1, 2])

In [80]:
np.setxor1d(m,n)


array([1, 2, 6, 7])

In [81]:
np.in1d(m,1)


array([ True, False, False, False, False])

In [82]:
m[np.in1d(m,1)]


array([1])

**np.clip**

In [84]:
a

array([42, 82, 81, 74,  5, 89, 19, 20, 17, 48, 86, 94, 10, 88, 13])

In [85]:
np.clip(a,a_min = 25,a_max = 75)

array([42, 75, 75, 74, 25, 75, 25, 25, 25, 48, 75, 75, 25, 75, 25])